definitions:
  main.Users:
    properties:
      age:
        description: Age
        example: 10
        type: integer
      id:
        description: UserId
        example: 1
        type: integer
      name:
        description: Name
        example: John
        type: string
    type: object
  repository.Search:
    properties:
      include_basic_aggs:
        example: true
        type: boolean
      pit:
        example: ""
        type: string
      query_string:
        example: performance
        type: string
      size:
        example: 10
        type: integer
      sort_order:
        example: DESC
        type: string
      start_date:
        example: 2021 01-01 00:00:00
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: test swagger api
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: test swagger api
  /es/search:
    post:
      consumes:
      - application/json
      description: search engine api
      parameters:
      - description: Search Info Body
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/repository.Search'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Search'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: search engine api
      tags:
      - Search
  /health:
    get:
      consumes:
      - application/json
      description: search engine health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: search engine health
      tags:
      - Search
  /hello/{name}:
    get:
      consumes:
      - application/json
      description: test swagger api
      parameters:
      - description: Users name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Users'
        "400":
          description: Bad Request
      summary: test swagger api
swagger: "2.0"
